import { IComboBoxOption, SelectableOptionMenuItemType } from "@fluentui/react";

export const GS_GRADES: IComboBoxOption[] = [
  { key: "GS", text: "GS", itemType: SelectableOptionMenuItemType.Header },
  { key: "GS-01", text: "GS-01" },
  { key: "GS-02", text: "GS-02" },
  { key: "GS-03", text: "GS-03" },
  { key: "GS-04", text: "GS-04" },
  { key: "GS-05", text: "GS-05" },
  { key: "GS-06", text: "GS-06" },
  { key: "GS-07", text: "GS-07" },
  { key: "GS-08", text: "GS-08" },
  { key: "GS-09", text: "GS-09" },
  { key: "GS-10", text: "GS-10" },
  { key: "GS-11", text: "GS-11" },
  { key: "GS-12", text: "GS-12" },
  { key: "GS-13", text: "GS-13" },
  { key: "GS-14", text: "GS-14" },
  { key: "GS-15", text: "GS-15" },
];

export const NH_GRADES: IComboBoxOption[] = [
  { key: "divider", text: "-", itemType: SelectableOptionMenuItemType.Divider },
  { key: "NH", text: "NH", itemType: SelectableOptionMenuItemType.Header },
  { key: "NH-02", text: "NH-02" },
  { key: "NH-03", text: "NH-03" },
  { key: "NH-04", text: "NH-04" },
  { key: "NH-05", text: "NH-05" },
];

export const MIL_GRADES: IComboBoxOption[] = [
  {
    key: "Enlisted",
    text: "Enlisted",
    itemType: SelectableOptionMenuItemType.Header,
  },
  { key: "E-1", text: "E-1" },
  { key: "E-2", text: "E-2" },
  { key: "E-3", text: "E-3" },
  { key: "E-4", text: "E-4" },
  { key: "E-5", text: "E-5" },
  { key: "E-6", text: "E-6" },
  { key: "E-7", text: "E-7" },
  { key: "E-8", text: "E-8" },
  { key: "E-9", text: "E-9" },
  { key: "divider", text: "-", itemType: SelectableOptionMenuItemType.Divider },
  {
    key: "Officer",
    text: "Officer",
    itemType: SelectableOptionMenuItemType.Header,
  },
  { key: "O-1", text: "O-1" },
  { key: "O-2", text: "O-2" },
  { key: "O-3", text: "O-3" },
  { key: "O-4", text: "O-4" },
  { key: "O-5", text: "O-5" },
  { key: "O-6", text: "O-6" },
  { key: "O-7", text: "O-7" },
  { key: "O-8", text: "O-8" },
  { key: "O-9", text: "O-9" },
  { key: "O-10", text: "O-10" },
];

export const OFFICES: IComboBoxOption[] = [
  { key: "XP-OZ", text: "XP-OZ" },
  { key: "divider", text: "-", itemType: SelectableOptionMenuItemType.Divider },
  { key: "OZA", text: "OZA" },
  { key: "divider", text: "-", itemType: SelectableOptionMenuItemType.Divider },
  { key: "OZI", text: "OZI" },
  { key: "OZIC", text: "OZIC" },
  { key: "OZIF", text: "OZIF" },
  { key: "OZIP", text: "OZIP" },
  { key: "divider", text: "-", itemType: SelectableOptionMenuItemType.Divider },
  { key: "OZJ", text: "OZJ" },
  { key: "divider", text: "-", itemType: SelectableOptionMenuItemType.Divider },
  { key: "OZJ", text: "OZJ", itemType: SelectableOptionMenuItemType.Header },
  { key: "divider", text: "-", itemType: SelectableOptionMenuItemType.Divider },
  { key: "OZO", text: "OZO" },
  { key: "divider", text: "-", itemType: SelectableOptionMenuItemType.Divider },
  { key: "OZT", text: "OZT" },
  { key: "divider", text: "-", itemType: SelectableOptionMenuItemType.Divider },
  { key: "OZZ", text: "OZZ" },
];
